add RGBA mode
pannacotta98/ogniewski-scaler pull request #6
Opened 2022-08-15 07:00 UTC by zvezdochiot

add RGBA mode (RGB*).

2022-08-21 15:31 UTC, pannacotta98 requested changes
👍

2022-08-21 15:31 UTC, pannacotta98 commented on src/render.c
> +                gdouble bc[3 * 3 * channels];  // 3x3 neighborhood, with RGB
Comment is no longer accurate

2022-08-21 15:41 UTC, zvezdochiot commented on src/render.c
> +                gdouble bc[3 * 3 * channels];  // 3x3 neighborhood, with RGB
Hi @pannacotta98 .

Maybe `// 3x3 neighborhood`

2022-08-26 17:31 UTC, pannacotta98 commented on src/render.c
> +                gdouble bc[3 * 3 * channels];  // 3x3 neighborhood, with RGB
Sounds fine to me :)

2022-08-26 18:16 UTC, zvezdochiot commented on src/render.c
> +                gdouble bc[3 * 3 * channels];  // 3x3 neighborhood, with RGB
Hi @pannacotta98 .
```c
                gdouble bc[3 * 3 * channels];  // 3x3 neighborhood
```
:heavy_check_mark:

2022-08-26 18:25 UTC, merged